### ISSUE TITLE
Discounted Price should be calculated in ConfirmPurchaseWindow and not passed as a parameter

### ISSUE THREAD

**Issue by OVGB** [eddsanity/OnlineStore#13]
https://github.com/eddsanity/OnlineStore/blob/de8cb03b76766966528d243a4d8e6faaf10229e5/OnlineStore/GUI%20forms/UserFunctions/PurchaseItemForm.cs#L96

**Comment by Youssef-Hammad** [comment]
It's pre calculated before the ConfirmPurchaseWindow to avoid the possible undefined behavior that might be caused due to the delay of accessing the online Database when opening the ConfirmPurchaseWindow
