### ISSUE TITLE
Since Handlers Logic is static, wouldn't it be better to make them singletons?

### ISSUE THREAD

**Issue by OVGB** [eddsanity/OnlineStore#16]

**Comment by eddsanity** [comment]
Singleton pattern isn't used when logic is static. It's used when a class needs to be ensured to have one and only one instance.
For us to need singleton handlers, we'd need to 1) have a shared resource that we'd like to control access to. 2) need to ensure that one and only one handler can be instantiated 3) access will be required by different parts of the system.
Our handlers have no such needs and therefore Singleton pattern isn't a good idea.
