### ISSUE TITLE
Database should info should not be accessible, and should be hidden in config files.

### ISSUE THREAD

**Issue by OVGB** [eddsanity/OnlineStore#8]
https://github.com/eddsanity/OnlineStore/blob/de8cb03b76766966528d243a4d8e6faaf10229e5/OnlineStore/App.config#L7

**Comment by eddsanity** [comment]
Irrelevant. This was a private repo and was only made public for you to review.

**Comment by eddsanity** [comment]
Irrelevant. This was a private repo and was only made public for you to review.
And it has nothing to do with what you're supposed to review.
